### PR TITLE
improve error messages by including info about user input

### PR DESCRIPTION
**Pull request by wgevaert**
Just a thought

### CODE REVIEW

**Comment by marijnvanwezel** [comment]
Thank you for your pull request. Please add unit tests testing the class you have added, as well as unit tests that test whether the right error message is thrown in the related functions.

**Comment by marijnvanwezel** [comment]
I think it would be better to rewrite the ErrorHelper into a `Trait` and rewrite the static methods to instance methods. These methods should not be part of the public API of a class, so I would also make them private. If you need any help with the implementation, please let me know.

**Comment by wgevaert** [comment]
I've done what you suggested.

**Comment by marijnvanwezel** [comment]
Thank you!

**Pull request merged**
