### PR TITLE
Literals

### PR DESCRIPTION
**Pull request by transistive**
Added some easier methods for working with literals.

There is now a `Literal::fromLiteral` method for easy creation, and a `ExpressionList::fromLiterals` method to work in an easier way with literals. This is a small step towards cleaning the API (https://github.com/WikibaseSolutions/php-cypher-dsl/issues/3), but not a solution.

Looking forward to your feedback :+1:

### CODE REVIEW

**Comment by 26** [comment]
Hi Ghlen, thank you for your pull request! What is the difference between the `Query::literal` function and the function `Literal::fromLiteral` you have added? It is probably better to write one in terms of the other.

I like the `fromLiterals` function you have added to create an expression list from a list of PHP literals, but I think it would be better to move that functionality to the `Query` class to keep the `ExpressionList` class purely about the syntactic representation of a list in Cypher. The best approach would probably be to rewrite the `Query::list` function so that it takes a mixed list of PHP-literals and `AnyType` objects. Let me know if you need assistance with the implementation.

**Comment by transistive** [comment]
Hi Marijn,

Thank you for the feedback! I moved it all to the Query class. This means the literal method has been reworked to accept Stringable types if that is ok. We can revert this is no problem.

What do you think?

**Comment by 26** [comment]
Hi Ghlen, looks good. I do not have enough time to review it in depth at the moment, but I will take a look at it tomorrow!

**Review by 26 — APPROVED** [review]
Looks good to me

**Comment by transistive** [comment]
Perfect, looking forward to seeing it merged :+1:

**Pull request merged**
